### PR TITLE
add CHANGELOG

### PR DESCRIPTION
**Pull request by jgravois**
this will make it more convenient for folks to see what has changed from one release to the next.

### CODE REVIEW

**Comment by jgravois** [comment]
i created two tags (using the commit date instead of today's date) to give a clearer idea of what i'm proposing. 

https://github.com/Esri/projection-engine-db-doc/compare/v2.1.0...v2.2.0

**Review by RJuergens — APPROVED** [review]

**Comment by jgravois** [comment]
thank you @RJuergens. i'll be on the lookout for the 2.3 changes soon.

**Comment by RJuergens** [comment]
Please check the security alerts associated with this repo.

**Comment by jgravois** [comment]
i added another changelog entry for 2.3, rebased the branch and addressed the security vulnerabilities (using [`npm audit`](https://docs.npmjs.com/cli/audit)).

if you're still happy with this PR i can merge and release on npm today.

**Comment by RJuergens** [comment]
looks OK

**Pull request merged**
