### PR TITLE
proj4-esri.txt: update implementation status for square conformal pro…

### PR DESCRIPTION
**Pull request by rouault**
…jections from libproject

Reflect incorporation into PROJ 7.1dev of libproject's square conformal projections per https://github.com/OSGeo/PROJ/pull/2148

### CODE REVIEW

**Comment by beuan** [comment]
Thank you, @rouault! Does `adams_ws2` supports all parameters as Esri does, or there are any differences we should be aware? I assume, it is sphere only.

**Comment by rouault** [comment]
> Does `adams_ws2` supports all parameters as Esri does, or there are any differences we should be aware? I assume, it is sphere only.

yes, currently, only sphere, and only scaleFactor = 1.0,  azimuth = 0.0, latitudeOfCenter = 0.0 and XYPlaneRotation = 0. We would certainly welcome hints on how to implement the general case :-)

**Comment by beuan** [comment]
So, you do not support Spilhaus case then?

**Comment by rouault** [comment]
> you do not support Spilhaus case then?

no, tracked as https://github.com/OSGeo/PROJ/issues/1851

**Comment by beuan** [comment]
OK. Thank you very much, @rouault. Once "hints" are published, I will let you know.

**Pull request merged**
