### PR TITLE
Prep for 3.4 git tag and npm release

### PR DESCRIPTION
**Pull request by beuan**
For details see #20.
cc @rgwozdz

### CODE REVIEW

**Comment by beuan** [comment]
@rgwozdz, I created v3.4.0 tag and push it to main. I leave npm package stuff to you. Let me know when you are done. Thanks!

**Comment by rgwozdz** [comment]
@beuan - the package-lock.json needs to be updated to reflect the version increment. I tried to do a PR but I am getting permission denied.

**Comment by rgwozdz** [comment]
@beuan - sorry about that, nevermind.  I see we don't commit the package-lock for this project.  I will publish and report back.

**Comment by rgwozdz** [comment]
Published 3.4.0 https://www.npmjs.com/package/@esri/proj-codes

**Pull request merged**
