### PR TITLE
Prep for 2.7 git tag and npm release

### PR DESCRIPTION
**Pull request by beuan**
For details see https://github.com/Esri/projection-engine-db-doc/pull/20
cc @jgravois, @rgwozdz, @ajturner

### CODE REVIEW

**Comment by beuan** [comment]
@jgravois 
I think I added all things for the npm stuff. Please check. Thanks.

**Comment by rgwozdz** [comment]
@beuan, FYI, @jgravois is no longer with Esri.  I'm happy to pick up his responsibilities on this.

**Comment by beuan** [comment]
That would be great. Thanks @rgwozdz!

**Review by rgwozdz — APPROVED** [review]

**Comment by beuan** [comment]
@rgwozdz, I created 2.7 tag and push it to master. I leave npm package stuff to you. Thanks!

**Comment by rgwozdz** [comment]
@beuan - I've published 2.7.0; https://www.npmjs.com/package/@esri/proj-codes

**Comment by jgravois** [comment]
hi guys! 👋 

> I created 2.7 tag 

i'm not seeing the [git tag](https://github.com/Esri/projection-engine-db-doc/tags) in the repo yet. after you push it up and merge #26 (just cosmetic cleanup), i'd call this good to go.

teamwork makes the dreamwork 🌈 

ref: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by beuan** [comment]
Fixed. You can see it now.

**Pull request merged**
