### PR TITLE
Prep for 3.0 git tag and npm release

### PR DESCRIPTION
**Pull request by beuan**
For details see #20.
cc @rgwozdz

### CODE REVIEW

**Review by RJuergens — APPROVED** [review]

**Comment by beuan** [comment]
@rgwozdz, I created v3.0.0 tag and push it to master. I leave npm package stuff to you. Let me know when you are done. Thanks!

**Comment by rgwozdz** [comment]
Thanks for the update @beuan.  I will publish and notify this thread later today.

**Comment by rgwozdz** [comment]
Published @esri/proj-codes@3.0.0

**Comment by beuan** [comment]
Thank you, @rgwozdz!

**Pull request merged**
